### PR TITLE
Publishes config, uses `passless.notification` config, fixes queueable notification seralization error.

### LINKED ISSUE #2: Config file does not get published, and 'passless.notification' config is ignored.
Framework: Laravel 5.8
PHP: 7.3.3

It is as the title suggests. When I run `php artisan vendor:publish --provider="DarkGhostHunter\Passless\PasslessServiceProvider"` with `v2.0.0`, the config file does not get copied.

In addition, when I manually copied the contents of `/config/passless.php` to my project, the `passless.notification` config is being ignored. The default `DarkGhostHunter\Passless\LoginNotification` is used, regardless of what I put in the config file.

### PR DESCRIPTION
**Pull request by spacenate**
This fixes #2 and #3, and adds a test for the notification serialization error.

### CODE REVIEW

**Review by DarkGhostHunter — CHANGES_REQUESTED** [review]
While the helpers functions like `config()` have nothing wrong, passing the implementations to the `_construct` allows to resolve the Service only one time, instead of many.

**Comment by spacenate** [comment]
That makes sense. In my testing, I found that having the services injected did not cause an error. It was only when storing a ref to the injected service (eg `$this->url = $url`) that the serialization error occurred.

It looks like no problem to have the `$config` injected, as the string values for `app.name` and `passless.lifetime` could be stored instead of a ref to $config itself.

Because `createLoginUrl()` is deferred (`Authenticatable $notifiable` is not available during instantiation), I am not sure how to get around calling the `app('url')` helper at that time. (See above comment about storing a ref to the injected `$url` service).

Would injecting `$config`, and then only calling `app('url')` once, be amenable to you? 

---

As a side note, I am curious; has anyone used this package in Laravel 5.8 as-is without running in to the serialization error?

**Comment by DarkGhostHunter** [comment]
> Would injecting `$config`, and then only calling `app('url')` once, be amenable to you?

For the time being, yes, since serializing closures is a limitation of PHP itself. Anyway, I'm gonna put that as a bug in Laravel, since from my point of view, if the Notification is Queueable, it should "clean" the dependencies, and then re-inject them on unserialization (also, makes the serialization lean). But that just my thougths.

> As a side note, I am curious; has anyone used this package in Laravel 5.8 as-is without running in to the serialization error?

I tested on a non-vanilla 5.8. I'll test that on the weekend. Time tight right now.

Update::

I will leave my comments on the code.

File: src/LoginNotification.php [hunk 1]
```diff
@@ -54,15 +38,11 @@ class LoginNotification extends Notification implements ShouldQueue
      *
      * @param bool $remember
      * @param string|null $intended
-     * @param Config $config
-     * @param Url $url
      */
-    public function __construct(bool $remember,?string $intended, Config $config, Url $url)
+    public function __construct(bool $remember,?string $intended)
```
Comment (DarkGhostHunter) [inline src/LoginNotification.php]: Re-inject the Config. It's okay to leave the `url()` to be called afterwards.

File: src/PasslessServiceProvider.php [hunk 2]
```diff
@@ -18,6 +18,8 @@ public function register()
         $this->mergeConfigFrom(
             __DIR__ . '/../config/passless.php', 'passless'
         );
+
+        $this->app->bind(LoginNotification::class, $this->app['config']['passless']['notification']);
```
Comment (DarkGhostHunter) [inline src/PasslessServiceProvider.php]: > "If the Service Container is called Service Container, it's because it contains fucking services.". -- Me, 2017.

It's better to set it in the [PasslessGuard](https://github.com/DarkGhostHunter/Passless/blob/master/src/PasslessGuard.php#L61). Did I forgot to add this? Was I too drunk?

```php
// Check first if the config has a notification class set. If there is one, we will tell the Service Container to
// instance it, and the return it so it can be sent. We will inject the Login Notification the "remember"
// and "intended" variables forcefully in the notification so the dev can use them at login time.
$notification = app('config')->get('passless.notification') ?? LoginNotification::class;

$notification = app()->make($notification, [
    'remember' => $remember,
    'intended' => $intended
]);

app(Dispatcher::class)->send($user, $notification);
```

File: src/PasslessServiceProvider.php [hunk 3]
```diff
@@ -29,6 +31,9 @@ public function boot()
     {
         $this->bootGuardDriver();
         $this->bootRoute();
+        $this->publishes([
```
Comment (DarkGhostHunter) [inline src/PasslessServiceProvider.php:32]: Yes, I forgot that.

**Comment by spacenate** [comment]
Requested changes have been completed :+1:

**Comment by DarkGhostHunter** [comment]
Everything is good from my end. All lights checks out. We're goin' places. Thank you!

**Comment by DarkGhostHunter** [comment]
Lol, closed it by mistake wtf.

**Comment by spacenate** [comment]
🙌
